### ISSUE TITLE
Would it be possible to allow symbolic-mangle to be built for musl on linux?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [getsentry/symbolic#880] opened 2024-12-01 13:53 UTC
When trying to do so, it seems to require `musl-g++`.

```
cargo build --target x86_64-unknown-linux-musl
   Compiling symbolic-demangle v12.12.3 (/home/andrew/workspace/symbolic/symbolic-demangle)
The following warnings were emitted during compilation:

warning: symbolic-demangle@12.12.3: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-g++` installed?
warning: symbolic-demangle@12.12.3: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-g++` installed?

error: failed to run custom build command for `symbolic-demangle v12.12.3 (/home/andrew/workspace/symbolic/symbolic-demangle)`

Caused by:
  process didn't exit successfully: `/home/andrew/workspace/symbolic/target/debug/build/symbolic-demangle-6e2e0a53b0f2c54a/build-script-build` (exit status: 1)
  --- stdout
  OUT_DIR = Some(/home/andrew/workspace/symbolic/target/x86_64-unknown-linux-musl/debug/build/symbolic-demangle-00aa62e8376c62ba/out)
  TARGET = Some(x86_64-unknown-linux-musl)
  OPT_LEVEL = Some(0)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-musl
  CXX_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_musl
  CXX_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CXX
  TARGET_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-g++` installed?
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(fxsr,sse,sse2)
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-musl
  CXXFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_musl
  CXXFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CXXFLAGS
  TARGET_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  OUT_DIR = Some(/home/andrew/workspace/symbolic/target/x86_64-unknown-linux-musl/debug/build/symbolic-demangle-00aa62e8376c62ba/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-g++` installed?
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some(fxsr,sse,sse2)
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-musl
  CXXFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_musl
  CXXFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CXXFLAGS
  TARGET_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None

  --- stderr


  error occurred: Failed to find tool. Is `musl-g++` installed?
```

**Comment by loewenheim** [comment] 2024-12-02 08:29
Can you install `musl-g++`?

**Comment by andrewdavidmackenzie** [comment] 2024-12-02 16:35
I couldn't find (quickly) a way to install it.

I read a number of blog posts and issues saying it should be musl-gcc, and
using x86_64-unknown-linux-gcc (or something like that) would do, but
without creating file links I didn't see how to make that work.

In the end, we dropped musl for now...

**Comment by Dav1dde** [comment] 2024-12-03 08:02
You can try cross compiling with [`cargo cross`](https://github.com/cross-rs/cross), it should have all the necessary gcc toolchains installed and setup.

**Comment by tobias-wilfert** [comment] 2024-12-10 13:52
Closing this for now, please repeon if the issue is not fixed by using [cargo cross](https://github.com/cross-rs/cross).

**Closed by tobias-wilfert** 2024-12-10 13:52 UTC

**Comment by prabhu** [comment] 2025-11-14 13:36
My fork https://github.com/AppThreat/multi-demangle has working CI for musl on linux. It is rewritten to use maturin.
