### ISSUE TITLE
`resolve_dsym` does not properly strip nested extensions

### ISSUE THREAD

**Issue by azhan1998** [getsentry/symbolic#451] opened 2021-11-18 11:25 UTC
`resolve_dsym` does not properly strip nested extensions, e.g. `.app` in `testApp.app.dSYM`. It attempts to look for a debug file under `testApp.app.dSYM/Contents/Resources/DWARF/testApp.app`, instead of the correct location at `testApp.app.dSYM/Contents/Resources/DWARF/testApp`.

**Comment by azhan1998** [comment] 2021-11-18 11:28
fn resolve_dsym(&self) -> Option<PathBuf> {
        if !self.is_dsym_dir() || !self.is_dir() {
            return None;
        }

        //for example

        let mut full_path = self.to_path_buf();
        full_path.push("Contents/Resources/DWARF");
        if full_path.is_dir() {
            let paths = fs::read_dir(full_path).unwrap();
            for path in paths {
                let mut full_path2 = path.unwrap().path();
                if full_path2.is_file() {
                    return Some(full_path2.to_path_buf());
                } else {
                    println!("file_name_error");
                    return None;
                }
            }
        }

        return None;
    }

**Comment by relaxolotl** [comment] 2021-11-19 00:52
Thanks for the report; It looks like `resolve_dsym` indeed doesn't strip the `.app` portion from the filename when resolving the path to the debug file.

 Out of curiosity, how did you generate or obtain the dSYM for your app? Was it through XCode, or some other tool?

**Comment by relaxolotl** [comment] 2021-11-19 00:56
I've also updated the description and title just to clarify what the issue is, and an extended explanation of the example that `resolve_dsyms` is unable to handle.

**Comment by azhan1998** [comment] 2021-11-19 02:11
> Out of curiosity, how did you generate or obtain the dSYM for your app? Was it through XCode, or some other tool?
>Xcode,sir

**Comment by azhan1998** [comment] 2021-11-19 02:21
> I've also updated the description and title just to clarify what the issue is, and an extended explanation of the example that `resolve_dsyms` is unable to handle.

your description  is correct,thanks

**Closed** 2021-11-24 01:26 UTC
Labels: bug

**Comment by azhan1998** [comment] 2021-12-01 08:24
It looks like resolve_dsym indeed doesn't strip the .framework portion from the filename when resolving the path to the debug file.
