### ISSUE TITLE
symbolic-minidump mishandling UnwindOperation::SetFPRegister?

### ISSUE THREAD

**Issue by Gankra** [getsentry/symbolic#546] opened 2022-04-27 15:50 UTC
Mozilla has some inline asm with some handwritten unwind tables, but it seems like dumpsyms isn't handling this line properly: https://searchfox.org/mozilla-central/rev/2c4522f76b23b024d9f29e140d41042853874c07/xpcom/reflect/xptcall/md/win32/xptcinvoke_asm_x86_64.asm#27

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1765243

**Comment by jrmuizel** [comment] 2022-04-27 15:58
SetFPRegister will also be used with any function that has a dynamic stack allocation:
https://gcc.godbolt.org/z/coYnoaWM3

It's not handled here:
https://github.com/getsentry/symbolic/blob/5e1bbb9a533ccc88aa28319462878f900fbabd19/symbolic-minidump/src/cfi.rs#L940

**Comment by Swatinem** [comment] 2022-04-27 16:52
>Establish the frame pointer register by setting the register to some offset of the current RSP. The offset is equal to the Frame Register offset (scaled) field in the UNWIND_INFO * 16, allowing offsets from 0 to 240. The use of an offset permits establishing a frame pointer that points to the middle of the fixed stack allocation, helping code density by allowing more accesses to use short instruction forms.

This will be interesting. So essentially we have to keep track of `stack_size` as we do now, but at the time of a `SetFPRegister`, we can probably say `.cfa = $rbp (or whatever the frame pointer register is) + stack_size - fp_offset * 16` or something similar.

```
        push    rbp
        .seh_pushreg rbp
        sub     rsp, 32
        .seh_stackalloc 32
        lea     rbp, [rsp + 32]
        .seh_setframe rbp, 32
```

So going by this example, `stack_size` would be 40 (as in: pushreg [8] + stackalloc [32]), and the offset should be 32?, which would leave us with `8`, which corresponds to the `pop rbp` from the epilog.

It could be I’m off by 8 or something, might be worth testing this out. I wonder if this might be the reason we can’t get through `RtlDispatchException` which I noticed some time ago.

**Comment by gabrielesvelto** [comment] 2022-04-28 07:58
> It could be I’m off by 8 or something, might be worth testing this out. I wonder if this might be the reason we can’t get through `RtlDispatchException` which I noticed some time ago.

Yes, that's very likely

**Comment by Swatinem** [comment] 2022-04-28 08:10
Another breadcrumb: a testcase that shows we can’t get through `RtlDispatchException` is here: https://github.com/getsentry/sentry-native/issues/582

**Comment by Swatinem** [comment] 2022-04-28 11:48
Yes, so `RtlDispatchException` does use this, which is great as I have a specific reproducible case to test this with.

Here is an unwind table dump for that specific function from `ntdll.dll`:

```
Function Table:
  Start Address: 0x51210
  End Address: 0x51578
  Unwind Info Address: 0x146454
    Version: 1
    Flags: 3 UNW_ExceptionHandler UNW_TerminateHandler
    Size of prolog: 48
    Number of Codes: 12
    Frame register: RBP
    Frame offset: 64
    Unwind Codes:
      0x1f: UOP_SaveNonVol RBX [0x0220]
      0x18: UOP_SetFPReg 
      0x13: UOP_AllocLarge 58
      0x0c: UOP_PushNonVol R15
      0x0a: UOP_PushNonVol R14
      0x08: UOP_PushNonVol R13
      0x06: UOP_PushNonVol R12
      0x04: UOP_PushNonVol RDI
      0x03: UOP_PushNonVol RSI
      0x02: UOP_PushNonVol RBP
```

**Comment by Swatinem** [comment] 2022-04-28 16:24
@Gankra do you have a specific minidump you can test this on?
I tried expanding the code in #549 but I somehow still can’t get through my own testcase that ends up in `RtlDispatchException`.

In particular, I transform the previously quoted unwind codes into:

```
STACK CFI INIT 51210 368 .cfa: $rbp 464 + $rbp: .cfa 16 - ^ $rsi: .cfa 24 - ^ $rdi: .cfa 32 - ^ $r12: .cfa 40 - ^ $r13: .cfa 48 - ^ $r14: .cfa 56 - ^ $r15: .cfa 64 - ^ $rbx: $rbp 480 + ^ .ra: .cfa 8 - ^
```

This does match up with the function epilogue:

```
18005155d: 48 8b 9d e0 01 00 00        	movq	480(%rbp), %rbx
180051564: 48 8d a5 90 01 00 00        	leaq	400(%rbp), %rsp
18005156b: 41 5f                       	popq	%r15
18005156d: 41 5e                       	popq	%r14
18005156f: 41 5d                       	popq	%r13
180051571: 41 5c                       	popq	%r12
180051573: 5f                          	popq	%rdi
180051574: 5e                          	popq	%rsi
180051575: 5d                          	popq	%rbp
180051576: c3                          	retq
```

here is the prologue just for completeness:

```
180051210: 40 55                       	pushq	%rbp
180051212: 56                          	pushq	%rsi
180051213: 57                          	pushq	%rdi
180051214: 41 54                       	pushq	%r12
180051216: 41 55                       	pushq	%r13
180051218: 41 56                       	pushq	%r14
18005121a: 41 57                       	pushq	%r15
18005121c: 48 81 ec d0 01 00 00        	subq	$464, %rsp              # imm = 0x1D0
180051223: 48 8d 6c 24 40              	leaq	64(%rsp), %rbp
180051228: 48 89 9d e0 01 00 00        	movq	%rbx, 480(%rbp)
```

**Comment by gabrielesvelto** [comment] 2022-04-28 16:48
I can test it on the minidumps from the bug referenced in the first comment. I'll give it a spin tomorrow.

**Closed** 2022-05-17 12:58 UTC
